### ISSUE TITLE
Debug difficulty

### ISSUE THREAD

**Issue by ArlindKadra** [automl/HpBandSter#11]
I was passing an unexpected output to BO-HB (worker part) and it was not progressing without reporting an error. The job was still running.

**Comment by sfalkner** [comment]
Hey Arlind, 
thanks for the issue. In order to do anything specific, it would be nice if you could provide a bit more detail on your issue (ideally a minimal working example). Right now I am not sure what you did and what you expected BOHB to do?

**Comment by ArlindKadra** [comment]
https://github.com/automl/HpBandSter/blob/251262765d3418cc581c920ba315c488f1f93194/hpbandster/examples/commons.py#L40

My first problem was a typo where I was accidentally passing the loss function instance and not the value inside it. In this case although I set the logger to debug level I got no error. I can recreate this and check it out again at a later time.
I also faced another problem when I was passing a numpy.ndarray in the output, BO-HB continued running in the cluster without progressing (the workers did not move on from trying to register the job part). This time however it showed on the logs as a serialization problem, changing the numpy.ndarray to a python list fixed the problem.
This implementation should showcase the second case, although as my code still needs a lot of refactoring the example toy function with a numpy.ndarray should do the trick:
https://github.com/ArlindKadra/DeepLearning/commit/9a63850ca4993a3f465da7c75270c024d03cd469

**Comment by sfalkner** [comment]
Hey Arlind,
I know this issue is pretty old and probably not relevant anymore, but I wanted to comment anyway.
I hope the documentation, especially the [best practices](https://automl.github.io/HpBandSter/build/html/best_practices.html), address your issue.
