### ISSUE TITLE
Race condition for super cheap computations

### ISSUE THREAD

**Issue by smoehrle** [automl/HpBandSter#13]
When we run a super cheap surrogate benchmark some runs do not terminate probably due to a race condition between the master and the dispatcher during the result registration process.

Greetings
Stefan

**Comment by sfalkner** [comment]
I couldn't really reproduce the issue, and by now I changed some parts of the code that might have caused that bug, so I am unsure if the problem still persists. I am going to close the issue for now, but please reopen if this becomes a problem again.
