### ISSUE TITLE
Example 3 - local parallel processes - stuck in a loop?

### ISSUE THREAD

**Issue by abhishek-ghose** [automl/HpBandSter#15]
When I attempt to run on Ubuntu, the program `hpbandster/examples/example_3_local_parallel_processes.py`, it seems stuck printing the following messages:

> INFO:hpbandster:DISPATCHER: started the 'discover_worker' thread
> INFO:hpbandster:DISPATCHER: started the 'job_runner' thread
> INFO:hpbandster:DISPATCHER: Pyro daemon running on localhost:42327
> INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
> INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
> INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
> INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
> INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker

The last line `INFO:hpbandster:...` keeps repeating (I counted ~250 times before I killed the code). Am I missing a step somewhere?

**Comment by abhishek-ghose** [comment]
I looked at the code - maybe these are _partly_ responsible for the errors?

1.This statement `parser.add_argument('--worker', help='Flag to turn this into a worker process', action='store_true')` actually leads to a default value of `False` for `args.worker` as per the [argparse source](https://hg.python.org/cpython/file/2.7/Lib/argparse.py#l861).
2. There is an `exit(0)` within the `if args.worker:` block - not sure if this is intended.
3. The `NameServer` is created after the workers are created. Should it before?
`

**Comment by sfalkner** [comment]
You will have to run the script in parallel in a different shell with the worker flag. The output you see shows that the master process is correctly running and waiting for more workers to join.

**Comment by abhishek-ghose** [comment]
Oh I see - that explains the `exit`. I will try this out later in the date and update here. Thank you!

**Comment by abhishek-ghose** [comment]
I tried this:
Ran the script `hpbandster/examples/example_3_local_parallel_processes.py` without the `--worker` flag in one shell (let's call it A). And in another shell, ran the same script with the flag (let's call it B).

Output from A before B starts - of course no changes yet:

> INFO:hpbandster:DISPATCHER: started the 'discover_worker' thread
> INFO:hpbandster:DISPATCHER: started the 'job_runner' thread
> INFO:hpbandster:DISPATCHER: Pyro daemon running on localhost:64000
> INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
> INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
> INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker

Output from B:

> INFO:hpbandster.run_example3.worker.ABC.14412:WORKER: start listening for jobs

Output from A after B starts:

> INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
> INFO:hpbandster:DISPATCHER: discovered new worker, hpbandster.run_example3.worker.ABC.14412
> INFO:hpbandster:HBMASTER: adjusted queue size to (0, 1)
> INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
> INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker

A now acknowledges worker B - 2nd line above. _However_ after that one line A goes back to printing `INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker` and B is stuck i.e. doesn't exit and no further output.

I am probably missing something obvious - how do i fix this? 

(I am not sure if this makes a difference, I am now running this on Windows, but I can check on Ubuntu too if it helps.)

**Comment by sfalkner** [comment]
Sorry for the delay, but I was on vacation.
Simply start the script with the worker flag a second time.If you
