### ISSUE TITLE
None of the sampled configurations was model_based

### ISSUE THREAD

**Issue by gchlebus** [automl/HpBandSter#20]
Hi, 

I found your library very interesting and I decided to give it a try. After first successful run I inspected the configs.json written by the json_result_logger class and I found out, that none of the tested configurations was sampled from the model (all configs had `"model_based_pick: false"`). Does it mean that all configurations were sampled randomly? Why is it so? I would expect that having model-based config pick should result in better configurations.

I would greatly appreciate your help.

**Comment by sfalkner** [comment]
Hey,
thanks for trying our package.
The fact that all configs were not picked by the model seems to suggest that there is something wrong. Could you please post your ConfigSpace defining the search space? Otherwise I can't tell you what might have happened.
Best, Stefan

**Comment by gchlebus** [comment]
Hi Stefan,

Please find below my ConfigSpace definition. Thanks for taking a look at it.
```
import ConfigSpace as cs

def get_configspace():
  config = cs.ConfigurationSpace()
  config.add_hyperparameter(cs.Constant('training_batchsize', 1))
  config.add_hyperparameter(cs.Constant('subbatch_validation', 1))
  config.add_hyperparameter(cs.Constant('validation_batchsize', 100))
  config.add_hyperparameter(cs.Constant('validation_interval', 400))
  config.add_hyperparameter(cs.CategoricalHyperparameter('loss_function', ['dice', 'categorical_cross_entropy',
                                                                           'dice_allchannels', 'top-k(5)']))
  config.add_hyperparameter(cs.UniformFloatHyperparameter('learning_rate', lower=1e-6, upper=1e-3, log=True))
  config.add_hyperparameter(cs.UniformFloatHyperparameter('arch_spatial_dropout', lower=0, upper=0.8,
                                                          default_value=0.5, log=False))
  config.add_hyperparameter(cs.CategoricalHyperparameter('arch_activation', ['relu', 'leaky_relu']))
  return config
```

**Comment by sfalkner** [comment]
Oh I see,
Could you try to remove the constants from your configspace.
I know the ConfigSpace has those, but I have never tested them, and so they probably don't work for BOHB. The reason it still runs through comes from the fact that BOHB will fall back to Hyperband if the configuration space has not supported features. You would see some messages in the debug output, but I guess I should make them warning that are always printed.
Sorry about that. Let me know if that fixes your problem.

**Comment by gchlebus** [comment]
Hi Stefan,
unfortunately, removal of Constants from the ConfigSpace didn't resolve the problem. Please find attached the sampled configs and results logged by the result logger (attached them as txt since github doesn't support json files). I started the optimization with min_budget=2 and max_budget=10. 
Do you have any idea, why still none of my configs was sampled from the model?

[results.txt](https://github.com/automl/HpBandSter/files/2481593/results.txt)
[config.txt](https://github.com/automl/HpBandSter/files/2481594/config.txt)

**Comment by gchlebus** [comment]
Hi Stefan,

Many thanks for your help. I just started next optimization run and will let you know once it ends. Could you elaborate a bit more on the types of iterations? What types of iterations are there and how the iteration type is chosen? I would appreciate a short explanation or a pointer to a code.

**Comment by sfalkner** [comment]
So Hyperband and BOHB do a round robin on different iterations that trade of an aggressive minimal budget with many configurations vs a conservative budget with only a few configurations.
I like the explanation [in the original Hyperand post](https://people.eecs.berkeley.edu/~kjamieson/hyperband.html), although their parametrization is slightly different.
So the basic idea is to have the first iteration start with the minimal budget and increase that by factors of eta (=3) and cutting down the number of configurations by the same factor. The next iteration will increase the smallest budget which means that fewer configurations are evaluated, but with a higher fidelity right  away.
This goes on until the iteration that just evaluates configurations on the largest budget. This is implemented in the code [here](https://github.com/automl/HpBandSter/blob/master/hpbandster/optimizers/bohb.py). You  only need to understand what self.budgets and what the ns variable in `get_next_iteration` are. Those will tell you how many configurations (`ns`) are evaluated at which budget.
BTW, I updated the FAQ to include your questions here.
Let me know if you any more questions, or close the issue if you are happy :)

**Comment by gchlebus** [comment]
As you expected, the next iteration picked some configurations from the model. Thank you very much for your help and the explanation of BOHP internals. Closing the issue.

**Comment by gui-miotto** [comment]
So, does it mean that BOHB fits a different model for every budget?
In other words, I'll only start evaluating (1 - **random_fraction**) of model sampled configurations after **min_points_in_model** configurations have been evaluated **for each budget** K. Is that it?

**Comment by gui-miotto** [comment]
Just for the record, config_space Constants work fine with BOHB. I've tested this.
