### ISSUE TITLE
Multiple optimizations on different GPUs

### ISSUE THREAD

**Issue by fenchri** [automl/HpBandSter#27]
Hello and thank you for this very interesting tool!

I have been trying to run several optimizations in parallel using different GPUs, i.e tune several NN models, each one using another GPU. 
I tried to do this similarly to example_3, by assigning a new worker to each model I want to tune. 
However, I need to give the same run_id to each worker that I gave to the master, otherwise the worker is stack listening for jobs.
I am afraid this way however, each model will influence the other because of the same run_id in the optimizer (BOHB).

Is there a another (correct) way to do this?

Thank you very much in advance

**Comment by sfalkner** [comment]
Hello, 

You cannot optimize different things in one run. To me it sounds like you want to start separate runs with different run_id's. The idea is that the run_id uniquely identifies one optimization run. If you start introducing different workers to the same run, there is no way for BOHB to distinguish between them, let alone optimize them separately. So the correct way would be to setup individual runs for each of your different workers. That includes a master and a run_id.
Hope that helps. Let me know if you have any more questions.
Please close the issue, if you feel like your question has been answered.

**Comment by fenchri** [comment]
Thank you for your answer. Yes, this setting makes sense to me, thanks again!
