### ISSUE TITLE
Sampling based optimization of the acquisition function

### ISSUE THREAD

**Issue by ifed-ucsd** [automl/HpBandSter#31]
Could you please explain the method by which samples are drawn in your library? I see you have:

`vector.append(sps.truncnorm.rvs(-m/bw,(1-m)/bw, loc=m, scale=bw))`

I'm confused about two things. In the paper, you say that the kernels for the KDE are Gaussian, but here you are sampling a truncated Gaussian. Second, I don't understand the truncation limits. It seems that the way you have it, you will only ever sample points less than m. I apologize if I'm misunderstanding something.

I appreciate your help!

**Comment by sfalkner** [comment]
Sorry for the late reply.
So the kernel of the KDE is based on Gaussians (without any truncation) as described in the paper.
For sampling from the kernel, we want to generate samples that are inside the defined bounds of each parameter. Those are defined in the ConfigSpace. To ensure that the sampled value is inside these bounds, we decided to sample from a truncated normal. We could have also sampled from the gaussian and rejected samples outside the bounds, but that seemed more of a hassle to code.

The rationale about the truncation limits is fairly simple:
1. The ConfigSpace automatically normalizes all continuous values to [0, 1].
2. See Note in [here](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.truncnorm.html)

Hope that helps!

**Comment by ifed-ucsd** [comment]
Thanks so much for the reply! That makes sense. I didn't realize that this normalization was happening under the hood.
