### ISSUE TITLE
optimizer for tasks with no meaningful budgets

### ISSUE THREAD

**Issue by akamaus** [automl/HpBandSter#34]
Hello!
I'm trying to use HpBandSter to do classical BO in a distributed fashion.
What's the best way to do optimization for tasks for which to such thing as a budget can be defined? I see there is RandomSearch optimizer, but is there a way to use model-based one? Of course one can use BOHB with fictive min_budget and max_budget values, but looks like that way several models will be trained (for different budgets), which is probably suboptimal.

**Comment by aaronkl** [comment]
simply set min-budget equal to max-budget, in order to force BO-HB to build only one model and thus become classic BO

**Comment by akamaus** [comment]
Indeed, it works. thanks!
