### ISSUE TITLE
Should I continuing a run by setting "result_logger = hpres.json_result_logger(directory=args.shared_directory, overwrite=False)"  overwrite=True?

### ISSUE THREAD

**Issue by tzc1994** [automl/HpBandSter#35]
Should I continuing a run by setting 
`result_logger = hpres.json_result_logger(directory=args.shared_directory, overwrite=False)` overwrite=True?
 If false, the program will make a error for `FileExistsError: The file ./configs.json already exists.`

**Comment by sfalkner** [comment]
Sorry for the late response.
I would strongly advise against using the overwrite flag for the following reason: If something goes wrong loading the data from the file, your results might be lost.
It is a better practice to give each run a truly unique run_id and store the data in a separate folder. This way, you never accidentally delete old runs.
