### ISSUE TITLE
Local runs without a server

### ISSUE THREAD

**Issue by KOLANICH** [automl/HpBandSter#38]
It may be problematic to embed the stuff into a library if it requires a separate process and a port to listen

**Comment by KOLANICH** [comment]
@sfalkner, it is just impolite to close issues without any hint why it was closed.

**Comment by sfalkner** [comment]
Let me briefly explain why I closed this and your other issue:
1. This one here is not really an issue, but you complaining that we made a deliberate design choice that is not going to change when designing our "stuff". I know the work flow is different from other optimizers, but that is on purpose, and we usually get good feedback when our tool is used in a parallel environment (mostly HPC clusters) which is it's main application.
Local parallelization is possible and most people are willing to spend the effort of taking the example scripts that show how to do that and adapt them to their needs. I am sure you can also adapt those scripts to embed the library if you only want to. We actually have a (early alpha) version of that running here: https://github.com/automl/Auto-PyTorch.
2. Your other issue was suggesting that you think that our "stuff" is inferior to your own project, and that we should rather spend our time incorporating our work into your library, which doesn't really encourage me to react to issues politely.
I hope that clarifies why I closed the issues.

**Comment by KOLANICH** [comment]
Thanks for the answer.
