### ISSUE TITLE
No model based picks with to many workers

### ISSUE THREAD

**Issue by JarnoRFB** [automl/HpBandSter#41]
I found that I do not get any model based picks when I run with to many workers. For example if I run the optimizer with
    
    min_n_workers = 8

I get model based picks when I run with 8 workers in total, but not when I run with 80 workers. Is this behavior known? Are there any recommendations for choosing the number of workers?

**Comment by sfalkner** [comment]
This behavior is totally expected. You can find an explanation [here in the best practices](https://automl.github.io/HpBandSter/build/html/best_practices.html#a-how-many-iterations-should-i-use).
The TLDR is, more workers make only sense if you run enough iterations.

**Comment by JarnoRFB** [comment]
Thanks for your answer. I could swear I read this passage several times... Anyway, after reading the section about parallelization in the paper again things became a lot clearer. I wrote a little function to understand how BOBH will behave given its hyperparameters in #43. Maybe that is useful for others as well.
