### ISSUE TITLE
Local working in MNIST example

### ISSUE THREAD

**Issue by bkj** [automl/HpBandSter#46]
Can you explain why you start a local worker in the MNIST example [here](https://github.com/automl/HpBandSter/blob/master/hpbandster/examples/example_5_mnist.py#L70).  Can I remove those lines safely?

**Comment by sfalkner** [comment]
You can just remove that line. Here is the rational: BOHB and the nameserver are computationally so cheap, that you can usually run an additional worker on the same node. But it's not a must.

**Comment by bkj** [comment]
Got it thanks

**Comment by sfalkner** [comment]
Could you please close the pull request if the issue is resolved? Thank you!
