### ISSUE TITLE
[1, 0, 1] meaning

### ISSUE THREAD

**Issue by sakalouski** [automl/HpBandSter#49]
Hi, I am struggling to find a meaning of lists of type [x,y,z] ([1,0,1]) in the keys of the optimization (results.json). I understand that this is a unique configuration, but what would be an interpretation? Where could I read about it?

Thanks!

**Comment by sfalkner** [comment]
It's not explicitly written anywhere, but if you want to know: The three integers mean: iteration, budget step, and sample index.
I assume Iteration is more or less clear.
The second index will tell you at what budget step inside the iteration this configuration was sampled. Unless a lot of your evaluations crash (or you have a different optimizer implemented this should always be zero.
The last one is just a running index inside the iteration.

The code that does that is [here](https://github.com/automl/HpBandSter/blob/master/hpbandster/core/base_iteration.py#L94).

Hope that helps.

**Comment by sakalouski** [comment]
Thanks a lot!
