### ISSUE TITLE
State of the project

### ISSUE THREAD

**Issue by PhilipMay** [automl/HpBandSter#70]
Hello,
this project is very interesting but I saw that it has no commit since Mar 26, 2019.
Just wanted to ask if it is still under development with a community or is it abandoned?
Thanks
Philip

**Comment by mlindauer** [comment]
Dear Philip,

Yes, the project is still active. Lately, we focused more on easy-to-use interfaces and examples, e.g., https://github.com/automl/BOAH

Best,
Marius

**Comment by PhilipMay** [comment]
Ok. Thanks.
