### ISSUE TITLE
Warmstarting BOHB and Hyperband

### ISSUE THREAD

**Issue by tschechlovdev** [automl/HpBandSter#71]
As far as I know, BOHB starts randomly Success Halving and then learns from the last SH iteration which configurations seem to be promising. Then depending on that, it starts the next SH iteration.
I am wondering if it is also possible to warm-start BOHB or Hyperband? So to tell which configurations should be tried in the first iteration?

**Comment by akamaus** [comment]
For BOHB it's certainly possible to warm-start by providing data to build initial model. Just pass `previous_result` argument.

**Comment by tschechlovdev** [comment]
Hi @akamaus,

thanks for your reply. I already found the example 8 that shows how to load previous results. But my problem is that I don't want to pass in the function evaluations but only to tell BOHB which configurations should be evaluated first. Is this somehow possible?

**Comment by akamaus** [comment]
Hmm, looks like I don't understand your idea then. Do you mean you have your plan of exploration config-space? If so, then maybe just evaluate configurations yourself and pass results as warm-start to BOHB?

**Comment by mfeurer** [comment]
We did something like this [for the 2nd AutoML challenge](https://ml.informatik.uni-freiburg.de/papers/18-AUTOML-AutoChallenge.pdf). You can find the source code [here](http://ml.informatik.uni-freiburg.de/downloads/automl_competition_2018.zip). The class `PortfolioBOHB` in the file `lib/hp_util.py` should do what you want (I can't guarantee that it works with the latest version of BOHB, though).

**Comment by tschechlovdev** [comment]
@mfeurer Thank you! I will give it a try.

**Comment by tschechlovdev** [comment]
@mfeurer I also had to include the ``SideShowBOHB`` class, but then it worked like a charm. Thanks!
