### ISSUE TITLE
some problem

### ISSUE THREAD

**Issue by sczhang870330** [automl/HpBandSter#99]
why appear this problem?
"""don't know how to serialize class <class 'numpy.intc'>. Give it vars() or an appropriate __getstate__"""
I have tried my best to debug but I can't eliminate this error, so please, thank you!!

**Comment by sfalkner** [comment]
Your workers `compute` method returns a `numpy.int` either as the loss or as part of the `info_dict`. Please convert all return values to python build-in types!
